apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventdisplay
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
