apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: pingsource
  namespace: default
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "test in progress"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventdisplay
